
version: '3.8'

services:
    buffalo:
      build:
        context: .
        dockerfile: ./.compose/buffalo/dockerfile
      command: sh /execute.sh
      environment: 
        - LC_ALL=C.UTF-8
      volumes:
        - ./buffalo:/app